/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.5.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { FunctionReference } from "convex/server";

// This is a stub for the Convex API. The actual implementation is generated by Convex.
// For full functionality, run `npx convex dev` to connect to your Convex backend.

type AnyApi = {
  [key: string]: {
    [key: string]: FunctionReference<any, any, any, any>;
  };
};

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api: AnyApi = {
  events: {
    listPublished: "events:listPublished" as unknown as FunctionReference<any, any, any, any>,
    listUpcoming: "events:listUpcoming" as unknown as FunctionReference<any, any, any, any>,
    getBySlug: "events:getBySlug" as unknown as FunctionReference<any, any, any, any>,
    getById: "events:getById" as unknown as FunctionReference<any, any, any, any>,
    search: "events:search" as unknown as FunctionReference<any, any, any, any>,
    create: "events:create" as unknown as FunctionReference<any, any, any, any>,
    update: "events:update" as unknown as FunctionReference<any, any, any, any>,
    updateStatus: "events:updateStatus" as unknown as FunctionReference<any, any, any, any>,
  },
  judging: {
    getQueue: "judging:getQueue" as unknown as FunctionReference<any, any, any, any>,
    submitComparison: "judging:submitComparison" as unknown as FunctionReference<any, any, any, any>,
  },
  leaderboard: {
    get: "leaderboard:get" as unknown as FunctionReference<any, any, any, any>,
  },
  registrations: {
    register: "registrations:register" as unknown as FunctionReference<any, any, any, any>,
    getByUser: "registrations:getByUser" as unknown as FunctionReference<any, any, any, any>,
    getByEvent: "registrations:getByEvent" as unknown as FunctionReference<any, any, any, any>,
  },
  submissions: {
    create: "submissions:create" as unknown as FunctionReference<any, any, any, any>,
    update: "submissions:update" as unknown as FunctionReference<any, any, any, any>,
    getByTeam: "submissions:getByTeam" as unknown as FunctionReference<any, any, any, any>,
    getByEvent: "submissions:getByEvent" as unknown as FunctionReference<any, any, any, any>,
  },
  teams: {
    create: "teams:create" as unknown as FunctionReference<any, any, any, any>,
    join: "teams:join" as unknown as FunctionReference<any, any, any, any>,
    leave: "teams:leave" as unknown as FunctionReference<any, any, any, any>,
    getByUser: "teams:getByUser" as unknown as FunctionReference<any, any, any, any>,
    getByInviteCode: "teams:getByInviteCode" as unknown as FunctionReference<any, any, any, any>,
  },
  users: {
    get: "users:get" as unknown as FunctionReference<any, any, any, any>,
    update: "users:update" as unknown as FunctionReference<any, any, any, any>,
  },
  waitlist: {
    join: "waitlist:join" as unknown as FunctionReference<any, any, any, any>,
  },
  seed: {
    seedDatabase: "seed:seedDatabase" as unknown as FunctionReference<any, any, any, any>,
  },
};

export const internal: AnyApi = api;
