// Generated route tree - in production this would be auto-generated by TanStack Router
import { createRootRoute, createRoute, createRouter, Outlet } from '@tanstack/react-router'
import { AppShell } from './components/layout/AppShell'
import { ToastProvider } from './components/ui/Toast'
import { RequireAuth, RequireRole } from './components/auth/RequireAuth'

// Pages
import { HomePage } from './pages/Home'
import { HackathonsPage } from './pages/hackathons/HackathonsList'
import { EventDetailPage } from './pages/hackathons/EventDetail'
import { RegisterPage } from './pages/hackathons/Register'
import { MyTeamPage } from './pages/teams/MyTeam'
import { CreateTeamPage } from './pages/teams/CreateTeam'
import { JoinTeamPage } from './pages/teams/JoinTeam'
import { SubmissionPage } from './pages/hackathons/Submission'
import { JudgingPage } from './pages/judging/JudgingQueue'
import { JudgingComparePage } from './pages/judging/JudgingCompare'
import { LeaderboardPage } from './pages/Leaderboard'
import { TownsquarePage } from './pages/stubs/Townsquare'
import { BuildathonPage } from './pages/stubs/Buildathon'
import { PowerOfCodePage } from './pages/stubs/PowerOfCode'
import { OpportunitiesPage } from './pages/stubs/Opportunities'
import { LoginPage } from './pages/auth/Login'
import { RegisterPage as AuthRegisterPage } from './pages/auth/Register'
import { ForgotPasswordPage } from './pages/auth/Forgot'
import { ResetPasswordPage } from './pages/auth/Reset'
import { MagicLinkPage } from './pages/auth/MagicLink'
import { VerifyCodePage } from './pages/auth/VerifyCode'
import { AdminEventsPage } from './pages/admin/Events'
import { AdminEventRegistrationsPage } from './pages/admin/EventRegistrations'
import { AdminEventRubricPage } from './pages/admin/EventRubric'
import { AdminEventJudgingPage } from './pages/admin/EventJudging'
import { AdminUsersPage } from './pages/admin/Users'

// Root layout
function RootLayout() {
  return (
    <ToastProvider>
      <AppShell>
        <Outlet />
      </AppShell>
    </ToastProvider>
  )
}

// Create root route
const rootRoute = createRootRoute({
  component: RootLayout,
})

// Index route
const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: HomePage,
})

// Hackathons routes
const hackathonsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/hackathons',
  component: HackathonsPage,
})

const eventDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/hackathons/$slug',
  component: EventDetailPage,
})

const registerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/hackathons/$slug/register',
  component: () => (
    <RequireAuth>
      <RegisterPage />
    </RequireAuth>
  ),
})

const submissionRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/hackathons/$slug/submission',
  component: () => (
    <RequireAuth>
      <SubmissionPage />
    </RequireAuth>
  ),
})

// Team routes
const myTeamRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/hackathons/$slug/team',
  component: () => (
    <RequireAuth>
      <MyTeamPage />
    </RequireAuth>
  ),
})

const createTeamRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/hackathons/$slug/team/create',
  component: () => (
    <RequireAuth>
      <CreateTeamPage />
    </RequireAuth>
  ),
})

const joinTeamRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/join/$inviteCode',
  component: () => (
    <RequireAuth>
      <JoinTeamPage />
    </RequireAuth>
  ),
})

// Judging routes
const judgingRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/judging/$eventSlug',
  component: () => (
    <RequireRole roles={['judge', 'admin', 'organizer']}>
      <JudgingPage />
    </RequireRole>
  ),
})

const judgingCompareRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/judging/$eventSlug/compare',
  component: () => (
    <RequireRole roles={['judge', 'admin', 'organizer']}>
      <JudgingComparePage />
    </RequireRole>
  ),
})

// Leaderboard
const leaderboardRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/leaderboard',
  component: () => (
    <RequireAuth>
      <LeaderboardPage />
    </RequireAuth>
  ),
})

// Stub routes
const townsquareRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/townsquare',
  component: TownsquarePage,
})

const buildathonRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/buildathon',
  component: BuildathonPage,
})

const powerOfCodeRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/power-of-code',
  component: PowerOfCodePage,
})

const opportunitiesRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/opportunities',
  component: OpportunitiesPage,
})

// Auth routes
const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/login',
  component: LoginPage,
})

const authRegisterRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/register',
  component: AuthRegisterPage,
})

const forgotRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/forgot',
  component: ForgotPasswordPage,
})

const resetRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/reset',
  component: ResetPasswordPage,
})

const magicLinkRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/magic-link',
  component: MagicLinkPage,
})

const verifyCodeRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/verify-code',
  component: VerifyCodePage,
})

// Admin routes
const adminEventsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/events',
  component: () => (
    <RequireRole roles={['admin', 'organizer']}>
      <AdminEventsPage />
    </RequireRole>
  ),
})

const adminRegistrationsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/events/$id/registrations',
  component: () => (
    <RequireRole roles={['admin', 'organizer']}>
      <AdminEventRegistrationsPage />
    </RequireRole>
  ),
})

const adminRubricRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/events/$id/rubric',
  component: () => (
    <RequireRole roles={['admin', 'organizer']}>
      <AdminEventRubricPage />
    </RequireRole>
  ),
})

const adminJudgingRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/events/$id/judging',
  component: () => (
    <RequireRole roles={['admin', 'organizer']}>
      <AdminEventJudgingPage />
    </RequireRole>
  ),
})

const adminUsersRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/users',
  component: () => (
    <RequireRole roles={['admin', 'organizer']}>
      <AdminUsersPage />
    </RequireRole>
  ),
})

// Build route tree
export const routeTree = rootRoute.addChildren([
  indexRoute,
  hackathonsRoute,
  eventDetailRoute,
  registerRoute,
  submissionRoute,
  myTeamRoute,
  createTeamRoute,
  joinTeamRoute,
  judgingRoute,
  judgingCompareRoute,
  leaderboardRoute,
  townsquareRoute,
  buildathonRoute,
  powerOfCodeRoute,
  opportunitiesRoute,
  loginRoute,
  authRegisterRoute,
  forgotRoute,
  resetRoute,
  magicLinkRoute,
  verifyCodeRoute,
  adminEventsRoute,
  adminRegistrationsRoute,
  adminRubricRoute,
  adminJudgingRoute,
  adminUsersRoute,
])
